TAG_VERSION = '版本號'

TAG_FILE_TYPE = '文件類型'
TAG_INPUT_METHOD = '輸入法'

TAG_FILE_TYPE_TEMPLATE = '範本'
TAG_FILE_TYPE_RADIX = '字根'
TAG_FILE_TYPE_COMPOSITION = '組字'

TAG_TEMPLATE_SET = '範本集'
TAG_TEMPLATE = '範本'
TAG_COMPOSITION_STRUCTURE = '組字結構'
TAG_COMPOSITION = '組字'
TAG_RADIX = '字根'

TAG_CHARACTER_SET = '字符集'
TAG_CHARACTER = '字符'

TAG_RULE_SET = '規則集'

TAG_NAME = '名稱'
TAG_STRUCTURE_SET = '結構集'
TAG_STRUCTURE = '結構'
TAG_OPERATOR = '運算'
TAG_REPLACEMENT = '置換'
TAG_MATCH = '比對'
TAG_SUBSTITUTE = '替換'

TAG_FONT_VARIANCE = '字體'
LIST__FONT_VARIANCE__TRADITIONAL = ['傳']
LIST__FONT_VARIANCE__SIMPLIFIED = ['簡']

