
FILE_ENCODING='utf-8-sig'

TAG_VERSION='版本號'

TAG_TEMPLATE_SET='範本集'
TAG_TEMPLATE='範本'
TAG_COMPOSITION_STRUCTURE='組字結構'
TAG_COMPOSITION='組字'
TAG_RADIX='字根'

TAG_CHARACTER_SET='字符集'
TAG_CHARACTER='字符'

TAG_PARAMETER_LIST='參數列'
TAG_PARAMETER='參數'

TAG_NAME='名稱'
TAG_OPERATOR='運算'
TAG_REPLACEMENT='置換'

TAG_CODE_INFORMATION='編碼資訊'


TAG_CODE_VARIANCE_TYPE="類型"
VALUE_CODE_VARIANCE_TYPE_STANDARD="標準"
VALUE_CODE_VARIANCE_TYPE_SIMPLIFIED="簡快"
VALUE_CODE_VARIANCE_TYPE_TOLERANT="容錯"

